---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: true
    customize:
      memory: 2048 
  run_list:
    - recipe[apt]
suites:
- name: service
  run_list: 
  - recipe[jira]
  attributes: {
    "java": {
      "jdk_version": '7',
      "install_flavor": "oracle",
      "oracle": {
        "accept_oracle_download_terms": true
      }
    }
  }
- name: postgresql
  run_list:
  - recipe[jira::database]
  attributes: {
    "postgresql": {
      "password": {
        "postgres": "dontcare"
      }
    }
  }
- name: mysql
  run_list:
  - recipe[jira::database]
  attributes: {
    "jira": {
      "database": {
        "type": "mysql"
      }
    },
    "mysql": {
      "server_root_password": "dontcare",
      "server_debian_password": "dontcare",
      "server_repl_password": "dontcare"
    }
  }
